// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAC3BSbIFqxhx7Dbf6Gb3hTduCLPY1Y9lU',
    appId: '1:421711278324:web:fb384580af0f432d2f6ea1',
    messagingSenderId: '421711278324',
    projectId: 'plantapplication-8cf7d',
    authDomain: 'plantapplication-8cf7d.firebaseapp.com',
    storageBucket: 'plantapplication-8cf7d.appspot.com',
    measurementId: 'G-WPF6W7T84V',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBnqYq6zDa_ZoQ_uL6Ugcz8GWturP7oFWA',
    appId: '1:421711278324:android:7514aef27a1f196b2f6ea1',
    messagingSenderId: '421711278324',
    projectId: 'plantapplication-8cf7d',
    storageBucket: 'plantapplication-8cf7d.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDB-CZtSZzcs3spHMsaUAV-2o4OSk57hfI',
    appId: '1:421711278324:ios:f6cedfcabec1a9af2f6ea1',
    messagingSenderId: '421711278324',
    projectId: 'plantapplication-8cf7d',
    storageBucket: 'plantapplication-8cf7d.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDB-CZtSZzcs3spHMsaUAV-2o4OSk57hfI',
    appId: '1:421711278324:ios:f6cedfcabec1a9af2f6ea1',
    messagingSenderId: '421711278324',
    projectId: 'plantapplication-8cf7d',
    storageBucket: 'plantapplication-8cf7d.appspot.com',
    iosBundleId: 'com.example.plantApp',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAC3BSbIFqxhx7Dbf6Gb3hTduCLPY1Y9lU',
    appId: '1:421711278324:web:03113570f6a176d82f6ea1',
    messagingSenderId: '421711278324',
    projectId: 'plantapplication-8cf7d',
    authDomain: 'plantapplication-8cf7d.firebaseapp.com',
    storageBucket: 'plantapplication-8cf7d.appspot.com',
    measurementId: 'G-YQ7K4P98JX',
  );

}